# FROM node:16

# WORKDIR /usr/src/app

# COPY e2e ./
# COPY src ./
# COPY . .
# COPY angular.json ./
# COPY browserslist ./
# COPY karma.conf.js ./
# COPY package*.json ./
# COPY proxy.conf.json ./
# COPY tsconfig*.json ./
# COPY tslint.json ./

# RUN npm install

# EXPOSE 4200

# CMD npm start

FROM node:10
WORKDIR /angular-app
COPY . .
RUN npm install @angular/cli && npm install

EXPOSE 4200

CMD npm start